http:
  routers:
    to-admin:
      tls: {}
      middlewares:
        - "block-all"
      rule: "PathPrefix(`/admin`)"
      service: backend
    to-backend:
      tls: {}
      rule: "PathPrefix(`/`)"
      service: backend
  middlewares:
    block-all:
      ipWhitelist:
        sourceRange:
          - "0.0.0.0/32"
  services:
    backend:
      loadBalancer:
        servers:
          - url: http://backend:8080/
tls:
  certificates:
    - certFile: /run/secrets/cert
      keyFile: /run/secrets/cert.key
