version: '3.9'
services:
  frontend:
    image: "${DOCKER_FRONTEND_IMAGE}"
    ports:
      - "443:443"
      - "443:443/udp"
    secrets:
      - source: certificate
        target: cert
      - source: certificate-key
        target: cert.key
  backend:
    image: "${DOCKER_BACKEND_IMAGE}"
    expose:
      - "8080"
secrets:
  certificate:
    file: "${DOCKER_DEV_CERTIFICATE}"
  certificate-key:
    file: "${DOCKER_DEV_CERTIFICATE_KEY}"
