version: '3.9'
services:
  hitch:
    image: martinvks/frontend_hitch
    ports:
      - "443:443"
    secrets:
      - source: certificate
        target: cert
      - source: certificate-key
        target: cert.key
  varnish:
    image: martinvks/frontend_varnish
    expose:
      - "80"
      - "8443"
  backend:
    image: "${DOCKER_BACKEND_IMAGE}"
    expose:
      - "8080"
secrets:
  certificate:
    file: "${DOCKER_DEV_CERTIFICATE}"
  certificate-key:
    file: "${DOCKER_DEV_CERTIFICATE_KEY}"