version: '3.9'
services:
  hitch:
    image: martinvks/frontend_hitch
    ports:
      - "443:443"
    secrets:
      - source: certificate-combined
        target: cert-combined
  varnish:
    image: martinvks/frontend_varnish
    expose:
      - "80"
      - "8443"
  backend:
    image: martinvks/backend_spring-boot-tomcat
    expose:
      - "8080"
secrets:
  certificate-combined:
    file: "${DOCKER_DEV_CERTIFICATE_COMBINED}"